name: Bump Homebrew Private Tap

on:
  release:
    types: [published]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formula
        run: |
          TAG=${{ gitea.event.release.tag_name }}
          VERSION=${TAG#v}
          git config --global user.name "gitea-actions"
          git config --global user.email "actions@gitea.roboalch.com"
          git clone https://roboalchemist:${{ secrets.TAP_TOKEN }}@gitea.roboalch.com/roboalchemist/homebrew-private.git
          cd homebrew-private
          sed -i "s|version \"[^\"]*\"|version \"${VERSION}\"|" Formula/opsgenie-cli.rb
          sed -i "s|tag: \"[^\"]*\"|tag: \"${TAG}\"|" Formula/opsgenie-cli.rb
          git add Formula/opsgenie-cli.rb
          git diff --cached --quiet && echo "No changes to commit" && exit 0
          git commit -m "opsgenie-cli: bump to ${TAG}"
          git push origin master
